import { NextResponse } from 'next/server';
import { requireStaff } from '@/lib/auth';

export const runtime = 'nodejs';

export async function POST(req: Request) {
  const { denied, profile, supabase } = await requireStaff();
  if (denied) {
    return NextResponse.json({ error: 'Not authorized' }, { status: 403 });
  }

  let body: any;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }

  const { header, lines, addonIds, addonItems } = body || {};
  if (!header || !Array.isArray(lines) || lines.length === 0) {
    return NextResponse.json({ error: 'Missing header or lines' }, { status: 400 });
  }
  if (!header.client_name) {
    return NextResponse.json({ error: 'client_name required' }, { status: 400 });
  }

  // ─── S-10 Approval workflow gates (Migration 075-aligned) ────────────────
  // Block save at the API layer when the quote crosses thresholds without
  // proper authorization. UI surfaces these as inline errors before submit.
  const discountPct = Number(header.discount_percent) || 0;
  const rights = header.rights_term_months || 0;
  if (discountPct > 25 && profile.role !== 'admin') {
    return NextResponse.json({
      error: 'Approval required',
      detail: `Discount ${discountPct}% exceeds 25% — requires Commercial + Finance approval. Ask an admin to ship this quote.`,
      code: 'APPROVAL_REQUIRED_DISCOUNT'
    }, { status: 403 });
  }
  if (rights >= 999 && profile.role !== 'admin') {
    return NextResponse.json({
      error: 'Approval required',
      detail: 'Perpetual rights require Legal + executive approval. Ask an admin to ship this quote.',
      code: 'APPROVAL_REQUIRED_PERPETUAL_RIGHTS'
    }, { status: 403 });
  }
  // Block when any line's final_unit is below the channel-adjusted base unless
  // an explicit override_reason is logged.
  if (Array.isArray(lines)) {
    const belowFloor = lines.find((l: any) => Number(l.final_unit) > 0
      && Number(l.base_rate) > 0
      && Number(l.final_unit) < Number(l.base_rate) * 0.5);
    if (belowFloor && !header.floor_override_reason) {
      return NextResponse.json({
        error: 'Floor override required',
        detail: `Line "${belowFloor.talent_name} · ${belowFloor.platform}" prices below 50% of base. Add header.floor_override_reason to log why before saving.`,
        code: 'FLOOR_OVERRIDE_REQUIRED'
      }, { status: 403 });
    }
  }

  // ─── Rights-territory + competitor blackout save gate (Mig 078) ──────────
  // The biggest hidden-margin lever: paid usage / exclusivity must be scoped.
  // Block save if rights are claimed (line.rights_pct > 0 OR header.rights_term_months > 0
  // OR header.exclusivity = true) AND the territory/competitors are not specified.
  const hasPaidRights = (Array.isArray(lines) && lines.some((l: any) => Number(l.rights_pct) > 0))
    || Number(header.rights_term_months) > 0
    || header.exclusivity === true;
  if (hasPaidRights && !header.rights_territory) {
    return NextResponse.json({
      error: 'Rights territory required',
      detail: 'Paid usage rights / exclusivity require rights_territory (KSA / GCC / MENA / Global). Undefined territory = margin leak — set header.rights_territory before saving.',
      code: 'RIGHTS_TERRITORY_REQUIRED'
    }, { status: 403 });
  }
  if (header.exclusivity === true && (!Array.isArray(header.competitor_blackout) || header.competitor_blackout.length === 0)) {
    return NextResponse.json({
      error: 'Competitor blackout list required',
      detail: 'Category exclusivity requires header.competitor_blackout — name the competitor brands blocked. Open exclusivity = future legal liability.',
      code: 'COMPETITOR_BLACKOUT_REQUIRED'
    }, { status: 403 });
  }

  // 1. Insert quote header (quote_number auto-generated by trigger)
  const { data: quote, error: qErr } = await supabase
    .from('quotes')
    .insert({ ...header, owner_id: profile.id })
    .select('id, quote_number, client_token')
    .single();
  if (qErr || !quote) {
    return NextResponse.json({ error: qErr?.message || 'Quote insert failed' }, { status: 500 });
  }

  // 2. Insert lines — including per-line axis overrides and computed social/floor prices
  const lineRows = lines.map((l: any) => ({
    quote_id: quote.id,
    sort_order: l.sort_order ?? 0,
    talent_type: l.talent_type,
    player_id: l.player_id ?? null,
    creator_id: l.creator_id ?? null,
    talent_name: l.talent_name,
    platform: l.platform,
    base_rate: l.base_rate ?? 0,
    qty: l.qty ?? 1,
    // Per-line axis overrides (null = inherit campaign axes)
    line_content_type: l.line_content_type ?? null,
    line_eng: l.line_eng ?? null,
    line_audience: l.line_audience ?? null,
    line_seasonality: l.line_seasonality ?? null,
    line_language: l.line_language ?? null,
    line_authority: l.line_authority ?? null,
    is_companion: !!l.is_companion,
    // Computed snapshot
    social_price: l.social_price ?? 0,
    floor_price: l.floor_price ?? 0,
    final_unit: l.final_unit ?? 0,
    final_amount: l.final_amount ?? 0,
  }));
  const { error: lErr } = await supabase.from('quote_lines').insert(lineRows);
  if (lErr) {
    // rollback header
    await supabase.from('quotes').delete().eq('id', quote.id);
    return NextResponse.json({ error: `Lines insert failed: ${lErr.message}` }, { status: 500 });
  }

  // 3. Insert add-on toggles (new shape: addonItems = [{addon_id, months}], legacy: addonIds = [id])
  type AddonItem = { addon_id: number; months: number };
  let items: AddonItem[] = [];
  if (Array.isArray(addonItems) && addonItems.length > 0) {
    items = addonItems
      .filter((x: any) => x && typeof x.addon_id === 'number')
      .map((x: any) => ({
        addon_id: x.addon_id,
        months: Math.max(1, Math.min(60, Math.round(x.months ?? 1))),
      }));
  } else if (Array.isArray(addonIds) && addonIds.length > 0) {
    items = addonIds.map((id: number) => ({ addon_id: id, months: 1 }));
  }

  if (items.length > 0) {
    const ids = items.map(i => i.addon_id);
    const { data: addonRows } = await supabase
      .from('addons')
      .select('id, uplift_pct')
      .in('id', ids);
    const byId = new Map((addonRows || []).map(a => [a.id, a.uplift_pct]));
    const upserts = items
      .filter(i => byId.has(i.addon_id))
      .map(i => ({
        quote_id: quote.id,
        addon_id: i.addon_id,
        uplift_pct: byId.get(i.addon_id),
        months: i.months,
      }));
    if (upserts.length > 0) {
      await supabase.from('quote_addons').insert(upserts);
    }
  }

  // 4. Audit log
  await supabase.from('audit_log').insert({
    actor_id: profile.id,
    actor_email: profile.email,
    action: 'quote.create',
    entity_type: 'quote',
    entity_id: quote.id,
    diff: { quote_number: quote.quote_number, status: header.status, total: header.total },
  });

  return NextResponse.json({
    id: quote.id,
    quote_number: quote.quote_number,
    client_token: quote.client_token,
  });
}
